### ISSUE TITLE
As a user I cannot create a post

### ISSUE THREAD

**Issue by voroninman** [mexehamy/blog2#4]
I visited the site but there is no any ability to create content and there is no content, so the site is useless for me as a user. :disappointed:

**Comment by mexehamy** [comment]
You right. I can't do it as a user too. Before I've created posts using superuser on http://localhost:8000/admin

I'll try to create registration for users.

**Comment by voroninman** [comment]
Great. I'll help you. Ask me anything whenever you are struggling.
